# Generated by Django 3.2.6 on 2024-09-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_especialidade', models.CharField(max_length=194, verbose_name='Especialidade')),
                ('data_inclusao', models.DateTimeField(auto_now=True, verbose_name='Data Inclusao')),
            ],
        ),
    ]
