# Generated by Django 3.2.6 on 2024-09-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'masculino'), ('F', 'feminino'), ('O', 'outro')], default=None, max_length=9, verbose_name='Sexo')),
                ('nome_completo', models.CharField(max_length=194, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('endereço', models.CharField(max_length=194, verbose_name='Endereço (rua, número e bairro)')),
                ('cidade', models.CharField(max_length=194, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=194, verbose_name='Estado')),
                ('email', models.EmailField(blank=True, max_length=194, null=True, verbose_name='E-mail')),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
    ]
