# Generated by Django 3.2.6 on 2024-09-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONSULTADO', 'Consultado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=126, verbose_name='Status de agendamento')),
                ('agendado_para', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicos.disponibilidade')),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicos.medicos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'agendamento',
            },
        ),
    ]
